//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改
//! This file is auto-generated by cozy-database-codegen, do not edit manually

/// BooksStatus 枚举
/// 对应表 books 的 status 字段
#[derive(Debug, Clone, PartialEq, Eq, sea_orm::DeriveActiveEnum, sea_orm::EnumIter, serde::Serialize, serde::Deserialize, ts_rs::TS)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum BooksStatus {
    #[sea_orm(string_value = "not_started")]
    NotStarted,
    #[sea_orm(string_value = "reading")]
    Reading,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "paused")]
    Paused,
}
