//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改
//! This file is auto-generated by cozy-database-codegen, do not edit manually

/// CommentType 枚举
/// 对应表 comments 的 comment_type 字段
#[derive(Debug, Clone, PartialEq, Eq, sea_orm::DeriveActiveEnum, sea_orm::EnumIter, serde::Serialize, serde::Deserialize, ts_rs::TS)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum CommentType {
    #[sea_orm(string_value = "note")]
    Note,
    #[sea_orm(string_value = "highlight")]
    Highlight,
    #[sea_orm(string_value = "bookmark")]
    Bookmark,
    #[sea_orm(string_value = "review")]
    Review,
}
