//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改
//! This file is auto-generated by cozy-database-codegen, do not edit manually

//! 数据库枚举类型（从 SQL CHECK 约束自动生成）

pub mod books_status;
pub use books_status::BooksStatus;
pub mod comment_type;
pub use comment_type::CommentType;
