use regex::Regex;
use std::fs;
use std::path::{Path, PathBuf};

/// 获取所有数据库名称（从文件系统扫描）
pub(crate) fn discover_databases(
    database_dir: &Path,
) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let src_dir = database_dir.join("src");
    let mut databases = Vec::new();

    if !src_dir.exists() {
        return Ok(databases);
    }

    let entries = fs::read_dir(&src_dir)?;

    for entry in entries {
        let entry = entry?;
        let path = entry.path();

        if !path.is_dir() {
            continue;
        }

        let dir_name = path.file_name().unwrap().to_string_lossy();
        if dir_name == "bin" || dir_name.starts_with('.') {
            continue;
        }

        // 检查是否包含 migrations 目录
        let migrations_dir = path.join("migrations");
        if migrations_dir.exists() && migrations_dir.is_dir() {
            databases.push(dir_name.to_string());
        }
    }

    Ok(databases)
}

/// 导出所有类型
pub fn export_types() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== 导出所有类型到 TypeScript ===");

    // 设置路径（从 build.rs 调用时，manifest_dir 是调用项目的目录）
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // 如果是从 tauri build.rs 调用，manifest_dir 是 crates/cozy-reader-tauri
    // 如果是从 database build.rs 调用，manifest_dir 是 crates/cozy-database
    // 如果是从 codegen 直接调用，manifest_dir 是 crates/cozy-database-codegen
    let project_root = if manifest_dir.ends_with("cozy-reader-tauri") {
        manifest_dir.parent().unwrap().parent().unwrap()
    } else if manifest_dir.ends_with("cozy-database") {
        manifest_dir.parent().unwrap()
    } else {
        manifest_dir.parent().unwrap().parent().unwrap()
    };
    let database_dir = project_root.join("crates/cozy-database");

    // 扫描所有数据库
    let databases = discover_databases(&database_dir)?;

    if databases.is_empty() {
        eprintln!("错误: 未找到任何数据库模块");
        return Err("未找到任何数据库模块".into());
    }

    println!("发现 {} 个数据库: {:?}", databases.len(), databases);

    // 导出错误类型
    println!("导出错误类型...");
    // DatabaseError 的导出路径已经在定义时指定，这里只需要触发编译

    // 注意：实体类型、服务输入类型和枚举类型的导出路径已经在各自的定义中指定
    // ts-rs 会在编译时自动生成 TypeScript 文件
    // 这里主要是添加 rerun-if-changed 检查，确保类型变更时重新生成

    // 生成 index.ts（基于代码结构，不扫描文件系统）
    generate_index_ts(&databases, &database_dir, project_root)?;

    println!("✅ 所有类型导出配置完成！");
    Ok(())
}

/// 生成统一的 index.ts 文件
/// 基于代码结构生成导出语句，不扫描文件系统（因为 ts-rs 生成的文件在编译后才存在）
fn generate_index_ts(
    databases: &[String],
    database_dir: &Path,
    project_root: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let index_file = project_root.join("packages/database/src/types/index.ts");
    let mut content = String::new();

    content.push_str("// 此文件由 cozy-database-codegen 自动生成，请勿手动修改\n");
    content.push_str(
        "// This file is auto-generated by cozy-database-codegen, do not edit manually\n\n",
    );
    content.push_str("// 导出所有生成的类型\n\n");

    // 导出错误类型
    content.push_str("export * from './generated/DatabaseError';\n\n");

    // 编译正则表达式一次（避免在循环中编译）
    let export_to_pattern = Regex::new(r#"export_to\s*=\s*"([^"]+)"#)?;

    // 为每个数据库生成导出
    for db_name in databases {
        content.push_str(&format!("// {} 数据库类型\n", db_name));

        // 导出实体类型（从 entities 目录扫描 Rust 文件）
        let entities_dir = database_dir.join(format!("src/{}/entities", db_name));
        if entities_dir.exists() {
            let entries = fs::read_dir(&entities_dir)?;
            for entry in entries {
                let entry = entry?;
                let path = entry.path();
                if path.is_file() {
                    if let Some(file_name) = path.file_name().and_then(|n| n.to_str()) {
                        if file_name.ends_with(".rs")
                            && file_name != "mod.rs"
                            && file_name != "lib.rs"
                            && file_name != "prelude.rs"
                        {
                            // 文件名：books.rs -> book.ts
                            let entity_name = extract_entity_name_from_file(file_name);
                            let ts_file = format!("{}.ts", entity_name);
                            content.push_str(&format!(
                                "export type {{ Model as {}Entity }} from './generated/{}/entities/{}';\n",
                                to_pascal_case(&entity_name),
                                db_name,
                                ts_file
                            ));
                        }
                    }
                }
            }
        }

        // 导出枚举类型（从 enums 目录扫描 Rust 文件）
        let enums_dir = database_dir.join(format!("src/{}/enums", db_name));
        if enums_dir.exists() {
            let entries = fs::read_dir(&enums_dir)?;
            for entry in entries {
                let entry = entry?;
                let path = entry.path();
                if path.is_file() {
                    if let Some(file_name) = path.file_name().and_then(|n| n.to_str()) {
                        if file_name.ends_with(".rs") && file_name != "mod.rs" {
                            // 文件名：books_status.rs -> booksStatus.ts
                            let enum_name = file_name.strip_suffix(".rs").unwrap_or(file_name);
                            let ts_file_name = to_camel_case_first_lower(enum_name);
                            let ts_file = format!("{}.ts", ts_file_name);
                            content.push_str(&format!(
                                "export * from './generated/{}/enums/{}';\n",
                                db_name, ts_file
                            ));
                        }
                    }
                }
            }
        }

        // 导出输入类型（从 services 目录扫描 Rust 文件，查找 export_to 属性）
        let services_dir = database_dir.join(format!("src/{}/services", db_name));
        if services_dir.exists() {
            let entries = fs::read_dir(&services_dir)?;
            for entry in entries {
                let entry = entry?;
                let path = entry.path();
                if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("rs") {
                    // 读取文件内容，查找 export_to 属性
                    if let Ok(file_content) = fs::read_to_string(&path) {
                        for cap in export_to_pattern.captures_iter(&file_content) {
                            if let Some(export_path) = cap.get(1) {
                                let export_path = export_path.as_str();
                                // 提取相对路径：从 packages/database/src/types/generated/... 开始
                                if let Some(relative_path) = export_path
                                    .split("packages/database/src/types/generated/")
                                    .nth(1)
                                {
                                    let ts_path =
                                        relative_path.strip_suffix(".ts").unwrap_or(relative_path);
                                    content.push_str(&format!(
                                        "export * from './generated/{}';\n",
                                        ts_path
                                    ));
                                }
                            }
                        }
                    }
                }
            }
        }

        content.push('\n');
    }

    fs::write(&index_file, content)?;
    println!("生成 index.ts: {:?}", index_file);
    Ok(())
}

/// 从文件名提取实体名称（books.rs -> book）
fn extract_entity_name_from_file(file_name: &str) -> String {
    let base_name = file_name.strip_suffix(".rs").unwrap_or(file_name);
    // 将复数形式转换为单数形式（简单规则）
    let name = if base_name.ends_with('s') && base_name.len() > 1 {
        base_name.strip_suffix('s').unwrap_or(base_name)
    } else {
        base_name
    };
    // 转换为小驼峰（snake_case -> camelCase）
    to_camel_case(name)
}

/// 转换为小驼峰（snake_case -> camelCase）
fn to_camel_case(s: &str) -> String {
    let parts: Vec<&str> = s.split('_').collect();
    if parts.is_empty() {
        return String::new();
    }
    let first = parts[0];
    let rest: String = parts[1..]
        .iter()
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect();
    format!("{}{}", first, rest)
}

/// 转换为 PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c.is_uppercase())
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut chars = s.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// 首字母小写（用于枚举文件名）
fn to_camel_case_first_lower(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
    }
}
