use regex::Regex;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub(crate) struct EnumInfo {
    pub name: String,
    pub values: Vec<String>,
    pub table: String,
    pub column: String,
    pub file_name: String,
}

pub(crate) fn extract_enums_from_sql(sql: &str) -> Vec<EnumInfo> {
    let mut enums = Vec::new();

    // 匹配 CHECK 约束中的枚举值
    // 例如: CHECK (status IN ('not_started', 'reading', 'completed', 'paused'))
    let check_pattern = Regex::new(r"(?i)CHECK\s*\(\s*(\w+)\s+IN\s*\(([^)]+)\)\s*\)").unwrap();

    // 匹配表名和列名
    let table_pattern = Regex::new(r"(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)").unwrap();

    let mut current_table = String::new();

    let value_pattern = Regex::new(r"'([^']+)'").unwrap();
    for line in sql.lines() {
        let trimmed = line.trim();

        // 检测表定义开始
        if let Some(caps) = table_pattern.captures(trimmed) {
            current_table = caps.get(1).unwrap().as_str().to_string();
            continue;
        }

        // 检测 CHECK 约束
        if let Some(caps) = check_pattern.captures(trimmed) {
            let column = caps.get(1).unwrap().as_str().to_string();
            let values_str = caps.get(2).unwrap().as_str();

            // 提取枚举值
            let values: Vec<String> = value_pattern
                .captures_iter(values_str)
                .map(|cap| cap.get(1).unwrap().as_str().to_string())
                .collect();

            if !values.is_empty() {
                // 生成枚举名称：使用列名（PascalCase），如果列名是通用名称则加上表名
                // 例如：status -> BookStatus, comment_type -> CommentType
                let enum_name = if column == "status" || column == "type" || column == "state" {
                    // 通用名称，加上表名前缀
                    format!("{}_{}", current_table, column)
                        .split('_')
                        .map(|s| {
                            let mut chars = s.chars();
                            match chars.next() {
                                None => String::new(),
                                Some(first) => {
                                    first.to_uppercase().collect::<String>() + chars.as_str()
                                }
                            }
                        })
                        .collect::<String>()
                } else {
                    // 使用列名（PascalCase）
                    column
                        .split('_')
                        .map(|s| {
                            let mut chars = s.chars();
                            match chars.next() {
                                None => String::new(),
                                Some(first) => {
                                    first.to_uppercase().collect::<String>() + chars.as_str()
                                }
                            }
                        })
                        .collect::<String>()
                };

                // 生成文件名称（snake_case）
                let file_name = if column == "status" || column == "type" || column == "state" {
                    format!("{}_{}", current_table, column)
                } else {
                    column.clone()
                };

                enums.push(EnumInfo {
                    name: enum_name,
                    values,
                    table: current_table.clone(),
                    column: column.clone(),
                    file_name,
                });
            }
        }
    }

    enums
}

fn generate_rust_enum(enum_info: &EnumInfo) -> String {
    let mut code = String::new();

    code.push_str("//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改\n");
    code.push_str(
        "//! This file is auto-generated by cozy-database-codegen, do not edit manually\n\n",
    );
    code.push_str(&format!("/// {} 枚举\n", enum_info.name));
    code.push_str(&format!(
        "/// 对应表 {} 的 {} 字段\n",
        enum_info.table, enum_info.column
    ));
    code.push_str(
        "#[derive(Debug, Clone, PartialEq, Eq, sea_orm::DeriveActiveEnum, sea_orm::EnumIter, serde::Serialize, serde::Deserialize, ts_rs::TS)]\n",
    );
    code.push_str("#[sea_orm(rs_type = \"String\", db_type = \"Text\")]\n");
    code.push_str(&format!("pub enum {} {{\n", enum_info.name));

    for value in &enum_info.values {
        // 将 snake_case 转换为 PascalCase
        let variant_name: String = value
            .split('_')
            .map(|s| {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            })
            .collect();

        code.push_str(&format!("    #[sea_orm(string_value = \"{}\")]\n", value));
        code.push_str(&format!("    {},\n", variant_name));
    }

    code.push_str("}\n");
    code
}

/// 首字母小写（用于枚举文件名）
fn to_camel_case_first_lower(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
    }
}

fn generate_typescript_enum(enum_info: &EnumInfo) -> String {
    let mut code = String::new();

    code.push_str("// 此文件由 cozy-database-codegen 自动生成，请勿手动修改\n");
    code.push_str(
        "// This file is auto-generated by cozy-database-codegen, do not edit manually\n\n",
    );
    code.push_str("/**\n");
    code.push_str(&format!(" * {} 枚举\n", enum_info.name));
    code.push_str(&format!(
        " * 对应表 {} 的 {} 字段\n",
        enum_info.table, enum_info.column
    ));
    code.push_str(" */\n");
    code.push_str(&format!("export enum {} {{\n", enum_info.name));

    for value in &enum_info.values {
        // 将 snake_case 转换为 PascalCase
        let variant_name: String = value
            .split('_')
            .map(|s| {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            })
            .collect();

        code.push_str(&format!("    {} = \"{}\",\n", variant_name, value));
    }

    code.push_str("}\n");
    code
}

/// 扫描 SQL 文件
fn scan_sql_files(migrations_dir: &Path) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let mut files = Vec::new();
    let entries = fs::read_dir(migrations_dir)?;

    for entry in entries {
        let entry = entry?;
        let path = entry.path();

        if path.is_file() {
            if let Some(ext) = path.extension() {
                if ext == "sql" {
                    files.push(path);
                }
            }
        }
    }

    files.sort();
    Ok(files)
}

/// 获取所有数据库名称（从文件系统扫描）
fn discover_databases(database_dir: &Path) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let src_dir = database_dir.join("src");
    let mut databases = Vec::new();

    if !src_dir.exists() {
        return Ok(databases);
    }

    let entries = fs::read_dir(&src_dir)?;

    for entry in entries {
        let entry = entry?;
        let path = entry.path();

        if !path.is_dir() {
            continue;
        }

        let dir_name = path.file_name().unwrap().to_string_lossy();
        if dir_name == "bin" || dir_name.starts_with('.') {
            continue;
        }

        // 检查是否包含 migrations 目录
        let migrations_dir = path.join("migrations");
        if migrations_dir.exists() && migrations_dir.is_dir() {
            // 检查 migrations 目录中是否有 SQL 文件
            if !scan_sql_files(&migrations_dir)?.is_empty() {
                databases.push(dir_name.to_string());
            }
        }
    }

    Ok(databases)
}

/// 生成枚举
pub fn generate_enums() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== 从 SQL 提取枚举类型（Database-First，多数据库支持）===");

    // 设置路径（从 build.rs 调用时，manifest_dir 是调用项目的目录）
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // 如果是从 tauri build.rs 调用，manifest_dir 是 crates/cozy-reader-tauri
    // 如果是从 database build.rs 调用，manifest_dir 是 crates/cozy-database
    // 如果是从 codegen 直接调用，manifest_dir 是 crates/cozy-database-codegen
    let project_root = if manifest_dir.ends_with("cozy-reader-tauri") {
        manifest_dir.parent().unwrap().parent().unwrap()
    } else if manifest_dir.ends_with("cozy-database") {
        manifest_dir.parent().unwrap()
    } else {
        manifest_dir.parent().unwrap().parent().unwrap()
    };
    let database_dir = project_root.join("crates/cozy-database");

    // 扫描所有数据库
    let databases = discover_databases(&database_dir)?;

    if databases.is_empty() {
        eprintln!("错误: 未找到任何数据库模块");
        return Err("未找到任何数据库模块".into());
    }

    println!("发现 {} 个数据库: {:?}", databases.len(), databases);

    // 为每个数据库生成枚举
    for db_name in &databases {
        println!("\n=== 处理数据库: {} ===", db_name);
        generate_enums_for_db(db_name, &database_dir, project_root)?;
    }

    println!("\n=== 所有数据库枚举生成完成 ===");
    Ok(())
}

/// 为单个数据库生成枚举
fn generate_enums_for_db(
    db_name: &str,
    database_dir: &Path,
    project_root: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let migrations_dir = database_dir.join(format!("src/{}/migrations", db_name));

    // 查找所有 SQL 迁移文件（按文件名排序）
    let sql_files = scan_sql_files(&migrations_dir)?;

    if sql_files.is_empty() {
        eprintln!("警告: 数据库 {} 没有找到 SQL 迁移文件", db_name);
        return Ok(());
    }

    // 合并所有 SQL 文件
    let mut sql = String::new();
    for sql_file in &sql_files {
        let content = fs::read_to_string(sql_file)?;
        sql.push_str(&content);
        sql.push('\n');
    }

    // 提取枚举
    let enums = extract_enums_from_sql(&sql);

    if enums.is_empty() {
        println!("未找到枚举类型");
        return Ok(());
    }

    println!("找到 {} 个枚举类型:", enums.len());
    for enum_info in &enums {
        println!(
            "  - {} (表: {}, 列: {})",
            enum_info.name, enum_info.table, enum_info.column
        );
    }

    // 生成 Rust 枚举
    let rust_output_dir = database_dir.join(format!("src/{}/enums", db_name));
    fs::create_dir_all(&rust_output_dir)?;

    let mut rust_mod_content = String::new();
    rust_mod_content.push_str("//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改\n");
    rust_mod_content.push_str(
        "//! This file is auto-generated by cozy-database-codegen, do not edit manually\n\n",
    );
    rust_mod_content.push_str("//! 数据库枚举类型（从 SQL CHECK 约束自动生成）\n\n");

    for enum_info in &enums {
        let rust_code = generate_rust_enum(enum_info);
        let file_name = format!("{}.rs", enum_info.file_name);
        let file_path = rust_output_dir.join(&file_name);
        fs::write(&file_path, rust_code)?;
        println!("生成 Rust 枚举: {:?}", file_path);

        rust_mod_content.push_str(&format!("pub mod {};\n", enum_info.file_name));
        rust_mod_content.push_str(&format!(
            "pub use {}::{};\n",
            enum_info.file_name, enum_info.name
        ));
    }

    // 生成 mod.rs
    let mod_file = rust_output_dir.join("mod.rs");
    fs::write(&mod_file, rust_mod_content)?;

    // 生成 TypeScript 枚举（文件名使用小驼峰：BooksStatus -> booksStatus.ts）
    let ts_output_dir = project_root.join(format!(
        "packages/database/src/types/generated/{}/enums",
        db_name
    ));
    fs::create_dir_all(&ts_output_dir)?;

    for enum_info in &enums {
        let ts_code = generate_typescript_enum(enum_info);
        // 枚举文件名：首字母小写，保持驼峰命名
        let ts_file_name = to_camel_case_first_lower(&enum_info.name);
        let file_name = format!("{}.ts", ts_file_name);
        let file_path = ts_output_dir.join(&file_name);
        fs::write(&file_path, ts_code)?;
        println!("生成 TypeScript 枚举: {:?}", file_path);
    }

    println!("数据库 {} 的枚举生成成功", db_name);
    Ok(())
}
