// 此文件由 build.rs 自动生成，请勿手动修改
// This file is auto-generated by build.rs, do not edit manually

use crate::config::DatabaseDefinition;

pub mod books;

pub use books::*;

/// 所有数据库定义
pub const DATABASES: &[DatabaseDefinition] = &[
    books::BOOKS_DEFINITION,
];
