//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改
//! This file is auto-generated by cozy-database-codegen, do not edit manually

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;
use crate::books::enums::BooksStatus;



#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "books")]
#[ts(export, export_to = "../../packages/database/src/types/generated/books/entities/book.ts")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[ts(type = "number")]
    pub id: i32,

    #[sea_orm(column_type = "Text", unique)]
    #[ts(type = "string")]
    pub path: String,

    #[sea_orm(column_type = "Text")]
    #[ts(type = "string")]
    pub title: String,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub author: Option<String>,

    #[sea_orm(column_type = "Text")]
    #[ts(type = "string")]
    pub format: String,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub cover: Option<String>,

    #[sea_orm(column_type = "Text")]
    #[ts(type = "string")]
    pub storage_type: String,

    #[ts(type = "number")]
    pub added_at: i32,

    #[ts(type = "number | null")]
    pub last_read_at: Option<i32>,

    #[sea_orm(column_type = "Text")]
    #[ts(type = "string")]
    pub current_progress: String,

    #[ts(type = "number")]
    pub total_characters: i32,

    #[ts(type = "number")]
    pub read_characters: i32,

    #[ts(type = "number")]
    pub reading_time_minutes: Decimal,

    #[ts(type = "number")]
    pub file_size: i32,

    #[ts(type = "BooksStatus")]
    pub status: BooksStatus,

    #[sea_orm(column_type = "Text")]
    #[ts(type = "string")]
    pub tags: String,

    #[ts(type = "number | null")]
    pub rating: Option<Decimal>,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub notes: Option<String>,

    #[ts(type = "number")]
    pub created_at: i32,

    #[ts(type = "number")]
    pub updated_at: i32,

    #[ts(type = "number | null")]
    pub deleted_at: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,
    #[sea_orm(has_many = "super::reading_sessions::Entity")]
    ReadingSessions,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::reading_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReadingSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
