//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改
//! This file is auto-generated by cozy-database-codegen, do not edit manually

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;
use crate::books::enums::CommentType;



#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "comments")]
#[ts(export, export_to = "../../packages/database/src/types/generated/books/entities/comment.ts")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[ts(type = "number")]
    pub id: i32,

    #[ts(type = "number")]
    pub book_id: i32,

    #[sea_orm(column_type = "Text")]
    #[ts(type = "string")]
    pub content: String,

    #[ts(type = "CommentType")]
    pub comment_type: CommentType,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub position_info: Option<String>,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub selected_text: Option<String>,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub color: Option<String>,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub tags: Option<String>,

    #[ts(type = "boolean | null")]
    pub is_private: Option<bool>,

    #[ts(type = "number")]
    pub created_at: i32,

    #[ts(type = "number")]
    pub updated_at: i32,

    #[ts(type = "number | null")]
    pub deleted_at: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::books::Entity",
        from = "Column::BookId",
        to = "super::books::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Books,
}

impl Related<super::books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Books.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
