//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改
//! This file is auto-generated by cozy-database-codegen, do not edit manually

//! 数据库实体（从数据库 Schema 自动生成）

pub mod books;
pub use books::Entity as BooksEntity;
pub mod comments;
pub use comments::Entity as CommentsEntity;
pub mod reading_sessions;
pub use reading_sessions::Entity as ReadingSessionsEntity;
