//! 此文件由 cozy-database-codegen 自动生成，请勿手动修改
//! This file is auto-generated by cozy-database-codegen, do not edit manually

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;



#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "reading_sessions")]
#[ts(export, export_to = "../../packages/database/src/types/generated/books/entities/readingSession.ts")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[ts(type = "number")]
    pub id: i32,

    #[ts(type = "number")]
    pub book_id: i32,

    #[ts(type = "number")]
    pub start_time: i32,

    #[ts(type = "number | null")]
    pub end_time: Option<i32>,

    #[ts(type = "number | null")]
    pub duration_minutes: Option<i32>,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub start_progress: Option<String>,

    #[sea_orm(column_type = "Text", nullable)]
    #[ts(type = "string | null")]
    pub end_progress: Option<String>,

    #[ts(type = "number | null")]
    pub characters_read: Option<i32>,

    #[ts(type = "number")]
    pub created_at: i32,

    #[ts(type = "number | null")]
    pub deleted_at: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::books::Entity",
        from = "Column::BookId",
        to = "super::books::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Books,
}

impl Related<super::books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Books.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
