[package]
name = "cozy-database"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

ts-rs = { workspace = true }
chrono = { version = "0.4.42", features = ["serde"] }
async-trait = { workspace = true }
thiserror = { workspace = true }
tauri-plugin-sql = { version = "^2.0.0", default-features = false }

[build-dependencies]
cozy-database-codegen = { path = "../cozy-database-codegen" }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
ts-rs = { workspace = true }
tempfile = { workspace = true }
