[package]
name = "cozy-reader"
version = "0.0.0"
description = "A Tauri App"
authors = ["srsng"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "cozy-reader-tauri"
path = "src/main.rs"
test = false

[build-dependencies]
tauri-build = { version = "2.3.1", features = [] }

[dependencies]
cozy-database = { path = "../cozy-database" }
regex = { workspace = true }
glob = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

log = "0.4"
tracing = { workspace = true }
tauri = { version = "2.7.0", features = ["protocol-asset"] }
tauri-plugin-log = "2"
tauri-plugin-store = "2"
tauri-plugin-sql = { features = ["sqlite"], version = "^2.0.0" }
tauri-plugin-fs = "2"
tauri-plugin-devtools = "2.0.0"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-os = "2.3.2"
tokio = { version = "1.47.1", features = ["fs"] }
chrono = { version = "0.4.42", features = ["serde"] }
ts-rs = "10.1.0"
mimetype-detector = "0.3.2"

[dev-dependencies]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2"

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
